### ISSUE TITLE
Twitter, no email address

### ISSUE THREAD

**Issue by bluebaroncompsci** [SocalNick/ScnSocialAuth#169]
There's no suitable flow for Twitter sign ins when you have the following settings in the zfcuser config.
    'enable_username' => false,
    'auth_identity_fields' => array( 'email' ),

//or 
    'enable_display_name' => false

**Comment by P0rnflake** [comment]
This is still an issue, facing that problem too...

**Comment by bluebaroncompsci** [comment]
Yup.  This is still an issue.  I've moved all my projects away from
ScnSocialAuth.  Also, in order to use doctrine, now, you have to use an old
version of zfcuser.  Abandonware.

**Comment by P0rnflake** [comment]
It is possible to run this module with doctrine and the latest stable of zfc-user (1.2.2). I am currently running this setup with "socalnick/scn-social-auth-doctrine-orm" in combination with "zf-commons/zfc-user-doctrine-orm" works out of the box, even with migrations. 

Maybe all we need is a check whether the user exists with the email / username before inserting and instead of insert an update should be called, or?
