### ISSUE TITLE
Redirect to login page and not logged

### ISSUE THREAD

**Issue by Colmea** [SocalNick/ScnSocialAuth#188]
Hello,
Thank's for this module, but I have some issues with Facebook and Google login.

Facebook login:
permission popup is opened and I'm able to authorize my app. But after, it redirects to my login page (url = /user/login#_=_). I'm not logged.

Google Login:
same here, popup is opened and permissions are asked. But after, it redirects to my login page, where I can see there's an error with the login form ("email is empty"... you don't say ?!). The form error only happens the first time. I'm not connected either.

Note: I don't have any errors (even atfer a deep debug in your module). But there is no data in the user_provider database.

Note2: I use the Doctrine adapter.

Thanks for your help and your work !

**Comment by SocalNick** [comment]
@Colmea - sorry for delayed response.

Is there any chance you could setup a simple test without the Doctrine adapter? I've actually never used it :)

If it turns out there is an issue with the Doctrine adapter, we can file the issue there and see about getting help from people using it.

**Comment by sergeypererva** [comment]
I think I have a relevant issue - the symptoms is the same after successful Google Authentication I redirected back to login page without any errors. I've put some time into debugging this and know the place the problem occurs, but for now I am not sure how I can fix it. The source of the problem is that [ScnSocialAuth\Authentication\Adapter\HybridAuth::autheticate()](https://github.com/SocalNick/ScnSocialAuth/blob/1.15.2/src/ScnSocialAuth/Authentication/Adapter/HybridAuth.php#L160) has no return (returns NULL always) but the calling code in [ZfcUser\Authentication\Adapter\AdapterChain::prepareForAuthentication()](https://github.com/ZF-Commons/ZfcUser/blob/1.2.2/src/ZfcUser/Authentication/Adapter/AdapterChain.php#L59) expects it to return instance of Response, the ZfcUser\Exception\AuthenticationEventException is thrown with message `Auth event was stopped without a response. Got "NULL" instead`. As I already told - I am not sure how to fix this but will continue with this tomorrow. 

Please, tell me if I am horribly wrong somewhere in my assumptions. Thanks.

**Comment by SocalNick** [comment]
Hi @sergeypererva,

Unfortunately, one assumption you've made is not accurate. [ZfcUser\Authentication\Adapter\AdapterChain::prepareForAuthentication()](https://github.com/ZF-Commons/ZfcUser/blob/1.2.2/src/ZfcUser/Authentication/Adapter/AdapterChain.php#L54) is triggering an authenticate event and passing an event object, it does not expect a Response. Responses only need to be returned when an event listener wants to short circuit the event: [ZF2 Event Manager](http://framework.zend.com/manual/current/en/modules/zend.event-manager.event-manager.html#examples).

Notice the identity is set on the [event object here](https://github.com/SocalNick/ScnSocialAuth/blob/1.15.2/src/ScnSocialAuth/Authentication/Adapter/HybridAuth.php#L153). If you've gotten to L153 in the authenticate method, something is likely happening in the next few lines when it tries to read and write the identity might be failing. If you can determine what is happening there, please open a new issue with said details.

**Comment by SocalNick** [comment]
@Colmea - closing due to no response
