### ISSUE TITLE
No entries in user_provider

### ISSUE THREAD

**Issue by hemmerich** [SocalNick/ScnSocialAuth#191]
I have it setup to where I am being properly redirected to Google, I login, approve the access, and then when I am redirected back to my application I am not authorized. This is on a public server (not a local server). There are no entries in the user_provider database table.

I am not certain where to start troubleshooting what I have setup incorrectly. Any advice would be very much appreciated!

I am also not certain how my existing users table would be mapped to google logins.

**Comment by P0rnflake** [comment]
I solved this kind of issue today by debugging a lot, because it can have several reasons.

At first you can ensure that the connection / oauth-communication works if you configure Hybrid_Auth debugging (http://hybridauth.sourceforge.net/userguide/Debugging_and_Logging.html) in 

      \socalnick\scn-social-auth\src\ScnSocialAuth\Service\HybridAuthFactory.php

In my case there was a bug with whitespaces, which were added to the client_id, so google responded with an error at the background API request.

If there is everything ok with the API requests itself, please check if you are using a custom user entity - this module depends on a fluid user interface, which is not state of the art in other modules which extend the zfc user module.

**Comment by SocalNick** [comment]
@P0rnflake thanks!!

@hemmerich does this help?

**Comment by hemmerich** [comment]
@P0rnflake thanks! I will need to reinstall everything and try again. I did not turn on the debugging you suggested. I did place my own debugging in ALL over the place and I am pretty confident it is an issue w/ the database connection. I am using doctrine ORM with a custom zfcuser user module.

@SocalNick I will have to give it a shot here in the next few days!

I appreciate the help! Thanks!

**Comment by Kakawet** [comment]
Using ScnSocialAuthDoctrineORM with a custom User Entity, same issue for me: login to google succed, approved access ok, but no acount created in database :s

Its working great with facebook and twitter, this issue is only for google Auth.

I don't know neither how to start debuging this ^^. I configure the hybridauth debugging has sugested by Pornflake,  but not whitespaces founded into tho client_id, like him.

No error found in the log, the last line is : 
Hybrid_Auth initialize: no error found. initialization succeed.

If it can help, you can found here the pastebin of the entire log: 
http://pastebin.com/FApQBKM5

Anyway, thank's for this module, apart that, realy easy to integrate   =)
